language: python
matrix:
  include:
  - env: TARGET=py2
  - env: TARGET=py3
  - env: TARGET=pep8
  - env: TARGET=mypy
  allow_failures:
  - env: TARGET=py3
  - env: TARGET=pep8
sudo: required
services:
- docker
install:
- true
script:
- travis_wait 30 docker build . -f .travis/${TARGET}.docker
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: Bgdzy6ApXMLF8R0DE+6P6EYmpu+HQMEXslilMskJ4Pvp6BTHolWpJuJrCaBP7N+kYR/ijO2yASME4/rrYcaCcSk/8p33EkFlNDruA7b2CfmPL23vCvn2Iv/4kO4n+VR539VdSgBc6vPofgzWi32LiZMp/UNokv+Qi+8Bimg6eVg=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ska-sa/purr
